name: Build Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: gradle build --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: glfencesyncfix
          path: build/libs/*.jar
